apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .names.ingress }}
  annotations:
    # automatically use cert-manager to get the cert:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    # necessary on GCP https://github.com/jetstack/cert-manager/issues/632
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
spec:
  tls:
  - hosts:
    - {{ .hostname }}
    secretName: {{ .hostname }}-tls
  rules:
  - host: {{ .hostname }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .names.service }}
          servicePort: 8000
