apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name {{ .Values.names.deployment }}
  labels: &labels
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  strategy:
    rollingUpdate:
      # workaround for the tiny beta box
      maxUnavailable: 100%
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: trustgator
        image: {{ .Values.image }}
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /vitals?src=deployment
            port: 8000
        env:
        {{- template "env.dbvars" .Values }}
        - name: FLASK_SECRET
          valueFrom:
            secretKeyRef: {name: {{ .Values.secret_names.session }}, key: key}
        - name: APP_MODE
          value: cloud
        - name: REDIS_SESSIONS
          value: {{ .Values.names.redis }}-service
        - name: REDIS_CACHES
          value: {{ .Values.names.redis }}-service
        resources: {requests: {cpu: "100m"}}
      {{- template "cloudsql.container" .Values }}
      volumes:
      {{- template "cloudsql.volume" .Values }}
